[project]
site_name = "SRDP – Single Repo Data Platform"
site_url = "https://docs.srdphub.com/"
repo_url = "https://github.com/srdp-hub/srdp"

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.markdown_extensions.footnotes]
